admin_personnalityType:
    resource:   "@AdminBundle/Resources/config/routing/personnalitytype.yml"
    prefix:     /personnalityType

#=================================#
#       MainController            #
#=================================#

admin_homepage:
    path:     /home
    defaults:
        _controller: AdminBundle:Main:home

admin_user:
    path:     /user
    defaults:
        _controller: AdminBundle:Main:user

admin_parameters:
    path:     /parameter
    defaults:
        _controller: AdminBundle:Main:parameters

admin_putParameters:
    path:     /putParameters
    defaults:
        _controller: AdminBundle:Parameters:putParameters

#=================================#
#   JobPersonnalityController     #
#=================================#

admin_job:
    path:     /job/{idJob}
    defaults:
        _controller: AdminBundle:JobPersonnality:job
    requirements:
        idJob: \d+

admin_jobs:
    path:     /jobs
    defaults:
        _controller: AdminBundle:JobPersonnality:jobs

admin_SavejobPersonnality:
    path:     /saveJobPersonnality
    defaults:
        _controller: AdminBundle:JobPersonnality:saveJobPersonnality

admin_jobPersonnality:
    path:     /jobPersonnality
    defaults:
        _controller: AdminBundle:JobPersonnality:jobPersonnality

admin_getPersonnalityType:
    path:     /getPersonnalityType/{idPersonnalityType}
    defaults:
        _controller: AdminBundle:JobPersonnality:getPersonnalityType

#=================================#
#       QuestionController        #
#=================================#

admin_questions:
    path:     /questions
    defaults:
        _controller: AdminBundle:Question:questions

admin_getResponsesFromQuestion:
    path:     /getResponsesFromQuestion/{questionId}
    defaults:
        _controller: AdminBundle:Question:responses
    requirements:
        questionId: \d+

admin_putQuestion:
    path:     /putQuestion
    defaults:
        _controller: AdminBundle:Question:questionPut

admin_deleteQuestion:
    path:     /deleteQuestion
    defaults:
        _controller: AdminBundle:Question:questionDelete

admin_postResponse:
    path:     /postResponse
    defaults:
        _controller: AdminBundle:Question:responsePost

admin_putResponse:
    path:     /putResponse
    defaults:
        _controller: AdminBundle:Question:responseUpdate

admin_deleteResponse:
    path:     /deleteResponse
    defaults:
        _controller: AdminBundle:Question:responseDelete