home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

test:
    resource: "@TestProjetBundle/Resources/config/routing.yml"
    prefix:   /test

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /uploadBundle

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"