test_homepage:
    path:     /
    defaults:
        _controller: TestBundle:Default:home

test_formOne:
    path:     /formOne
    defaults:
        _controller: TestBundle:Default:formOne

test_formTwo:
    path:     /formTwo
    defaults:
        _controller: TestBundle:Default:formTwo