admin_job_home:
    path:     /
    defaults:
        _controller: AdminBundle:JobTemperament:jobs
        method: [GET, POST]

admin_postJob:
    path:     /post
    defaults:
        _controller: AdminBundle:JobTemperament:postJob
        method: POST

admin_job:
    path:     /{idJob}
    defaults:
        _controller: AdminBundle:JobTemperament:job
        method: [GET, POST]
    requirements:
        idJob: \d+

admin_deleteJob:
    path:     /{idJob}/delete
    defaults:
        _controller: AdminBundle:JobTemperament:deleteJob
        method: DELETE

admin_putJob:
    path:     /{idJob}/put
    defaults:
        _controller: AdminBundle:JobTemperament:putJob
        method: POST

admin_save:
    path:     /{idJob}/saveTemperament
    defaults:
        _controller: AdminBundle:JobTemperament:saveJobTemperament
        method: POST


admin_getTemperament:
    path:     /getTemperament/{idTemperament}
    defaults:
        _controller: AdminBundle:JobTemperament:getTemperament
        method: GET