admin_parameter:
    path:     /
    defaults:
        _controller: AdminBundle:Main:parameters
        method: [GET, POST]

admin_putParameters:
    path:     /put/{idParameter}
    defaults:
        _controller: AdminBundle:Main:updateParameters
        method: POST

admin_mentionLegale:
    path:     /mentionLegale
    defaults:
        _controller: AdminBundle:Main:mentionLegale
        method: POST
