admin_temperament_show:
    path:   /
    defaults:
        _controller: AdminBundle:Temperament:temperament

temperament_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Temperament:delete" }
