admin_temperament_show:
    path:   /
    defaults:
        _controller: AdminBundle:Temperament:temperament
        method: GET

temperament_delete:
    path:     /delete/{id}
    defaults:
        _controller: AdminBundle:Temperament:delete
