AdminBundle\Entity\Job:
    type: entity
    table: JOB
    repositoryClass: AdminBundle\Repository\JobRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '45'
            unique: true
        slug:
            type: string
            length: '255'
            gedmo:
                slug:
                    separator: _
                    style: lower
                    fields:
                        - name
        description:
            type: text
        minSalary:
            type: integer
        maxSalary:
            type: integer
        imageName:
            type: string
            length: '255'
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
        deliveredByQuizz:
            type: integer
    indexes:
        search_idx:
          columns: slug
    oneToMany:
        jobTemperaments:
            targetEntity: AdminBundle\Entity\JobTemperament
            mappedBy: job
            cascade: [persist, remove]
    lifecycleCallbacks: {  }
