AdminBundle\Entity\Job:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\JobRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '45'
            unique: true
        description:
            type: text
        salaireMin:
            type: integer
        salaireMax:
            type: integer
    oneToMany:
        jobPersonnalities:
            targetEntity: AdminBundle\Entity\JobPersonnality
            mappedBy: job
    lifecycleCallbacks: {  }
