AdminBundle\Entity\JobPersonnality:
    type: entity
    table: JOB_PERSONNALITY
    repositoryClass: AdminBundle\Repository\JobPersonnalityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: integer
    manyToOne:
        job:
            targetEntity: AdminBundle\Entity\Job
            inversedBy: jobPersonnalities
        temperament:
            targetEntity: AdminBundle\Entity\Temperament
            inversedBy: jobPersonnalities
    lifecycleCallbacks: {  }
