AdminBundle\Entity\PersonnalityType:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\PersonnalityTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '45'
            unique: true
        personnalityType:
            type: string
            length: '45'
            unique: true
        opposedPersonnalityType:
            type: string
            length: '45'
            unique: true
    oneToMany:
        jobPersonnalities:
            targetEntity: AdminBundle\Entity\JobPersonnality
            mappedBy: personnalityType
    lifecycleCallbacks: {  }
