AdminBundle\Entity\Response:
    type: entity
    table: RESPONSE
    repositoryClass: AdminBundle\Repository\ResponseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: '45'
        value:
            type: integer
        imageName:
            type: string
            length: '45'
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
    manyToOne:
        question:
            targetEntity: AdminBundle\Entity\Question
            inversedBy: responses
        temperament:
            targetEntity: AdminBundle\Entity\Temperament
            inversedBy: responses
    lifecycleCallbacks: {  }
