AdminBundle\Entity\Temperament:
    type: entity
    table: TEMPERAMENT
    repositoryClass: AdminBundle\Repository\TemperamentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '45'
            unique: true
        temperament:
            type: string
            length: '45'
            unique: true
        opposedTemperament:
            type: string
            length: '45'
            unique: true
    oneToMany:
        jobPersonnalities:
            targetEntity: AdminBundle\Entity\JobPersonnality
            mappedBy: temperament
            cascade: [persist, remove]
        responses:
            targetEntity: AdminBundle\Entity\Response
            mappedBy: temperament
            cascade: [persist, remove]
    lifecycleCallbacks: {  }
