home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Home:index }

home_metiers:
    path:     /metiers
    defaults: { _controller: HomeBundle:Home:metiers }

home_question1:
    path:     /question1
    defaults: { _controller: HomeBundle:Home:question1 }

home_question2:
    path:     /question2
    defaults: { _controller: HomeBundle:Home:question2 }

home_metier:
    path:     /metier
    defaults: { _controller: HomeBundle:Home:metier }

home_mentionsLegales:
    path:     /mentionsLegales
    defaults: { _controller: HomeBundle:Home:mentionsLegales }


